package com.xx.mylauncher.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CELL_INFO_ENTITY.
 */
public class CellInfoEntity {

    private Long id;
    private Integer cellType;
    private Integer cellLocation;
    private Integer cellX;
    private Integer cellY;
    private Integer cellHSpan;
    private Integer cellVSpan;
    private String iconName;
    private Integer screen;
    private Integer hotseatCellX;
    private Integer hotseatCellY;
    private Integer widgetid;
    private String labelName;
    private String pkgName;
    private String clsName;

    public CellInfoEntity() {
    }

    public CellInfoEntity(Long id) {
        this.id = id;
    }

    public CellInfoEntity(Long id, Integer cellType, Integer cellLocation, Integer cellX, Integer cellY, Integer cellHSpan, Integer cellVSpan, String iconName, Integer screen, Integer hotseatCellX, Integer hotseatCellY, Integer widgetid, String labelName, String pkgName, String clsName) {
        this.id = id;
        this.cellType = cellType;
        this.cellLocation = cellLocation;
        this.cellX = cellX;
        this.cellY = cellY;
        this.cellHSpan = cellHSpan;
        this.cellVSpan = cellVSpan;
        this.iconName = iconName;
        this.screen = screen;
        this.hotseatCellX = hotseatCellX;
        this.hotseatCellY = hotseatCellY;
        this.widgetid = widgetid;
        this.labelName = labelName;
        this.pkgName = pkgName;
        this.clsName = clsName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCellType() {
        return cellType;
    }

    public void setCellType(Integer cellType) {
        this.cellType = cellType;
    }

    public Integer getCellLocation() {
        return cellLocation;
    }

    public void setCellLocation(Integer cellLocation) {
        this.cellLocation = cellLocation;
    }

    public Integer getCellX() {
        return cellX;
    }

    public void setCellX(Integer cellX) {
        this.cellX = cellX;
    }

    public Integer getCellY() {
        return cellY;
    }

    public void setCellY(Integer cellY) {
        this.cellY = cellY;
    }

    public Integer getCellHSpan() {
        return cellHSpan;
    }

    public void setCellHSpan(Integer cellHSpan) {
        this.cellHSpan = cellHSpan;
    }

    public Integer getCellVSpan() {
        return cellVSpan;
    }

    public void setCellVSpan(Integer cellVSpan) {
        this.cellVSpan = cellVSpan;
    }

    public String getIconName() {
        return iconName;
    }

    public void setIconName(String iconName) {
        this.iconName = iconName;
    }

    public Integer getScreen() {
        return screen;
    }

    public void setScreen(Integer screen) {
        this.screen = screen;
    }

    public Integer getHotseatCellX() {
        return hotseatCellX;
    }

    public void setHotseatCellX(Integer hotseatCellX) {
        this.hotseatCellX = hotseatCellX;
    }

    public Integer getHotseatCellY() {
        return hotseatCellY;
    }

    public void setHotseatCellY(Integer hotseatCellY) {
        this.hotseatCellY = hotseatCellY;
    }

    public Integer getWidgetid() {
        return widgetid;
    }

    public void setWidgetid(Integer widgetid) {
        this.widgetid = widgetid;
    }

    public String getLabelName() {
        return labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public String getPkgName() {
        return pkgName;
    }

    public void setPkgName(String pkgName) {
        this.pkgName = pkgName;
    }

    public String getClsName() {
        return clsName;
    }

    public void setClsName(String clsName) {
        this.clsName = clsName;
    }

}
